<?php
$z[0]=Array("arcurl","",73,88);
$z[1]=Array("picname","",119,135);
$z[2]=Array("picname","",142,158);
$z[3]=Array("title","",190,204);
$z[4]=Array("arcurl","",434,449);
$z[5]=Array("title","",473,487);
$z[6]=Array("title","",489,503);
$z[7]=Array("pubdate","",620,667);
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("dows","",728,741);
$z[9]=Array("dows","",778,791);
$z[10]=Array("click","",838,852);
$z[11]=Array("click","",888,902);
$z[12]=Array("stows","",950,964);
$z[13]=Array("stows","",1016,1030);

?>