<?php
$z[0]=Array("picname","",215,231);
$z[1]=Array("picname","",238,254);
$z[2]=Array("title","",286,300);
$z[3]=Array("title","",607,621);
$z[4]=Array("title","",623,637);
$z[5]=Array("pubdate","",754,801);
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("dows","",869,882);
$z[7]=Array("dows","",919,932);
$z[8]=Array("click","",979,993);
$z[9]=Array("click","",1029,1043);
$z[10]=Array("stows","",1091,1105);
$z[11]=Array("stows","",1157,1171);

?>