<?php
$z[0]=Array("picname","",134,150);
$z[1]=Array("picname","",157,173);
$z[2]=Array("title","",205,219);
$z[3]=Array("title","",526,540);
$z[4]=Array("title","",542,556);
$z[5]=Array("pubdate","",673,720);
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("dows","",788,801);
$z[7]=Array("dows","",838,851);
$z[8]=Array("click","",898,912);
$z[9]=Array("click","",948,962);
$z[10]=Array("stows","",1010,1024);
$z[11]=Array("stows","",1076,1090);

?>