<?php
$z[0]=Array("title","",125,139);
$z[1]=Array("arcurl","",147,162);
$z[2]=Array("title","",200,214);
$z[3]=Array("picname","",231,247);
$z[4]=Array("global","",254,280);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("arcurl","",376,391);
$z[6]=Array("title","",400,414);
$z[7]=Array("title","",416,430);
$z[8]=Array("description","",538,587);
$z[8][4]['function']="cn_substr(@me,60)";
$z[9]=Array("needmoney","",677,695);
$z[10]=Array("arcurl","",747,762);

?>