<li> 
        <div class="item"> 
         <div class="basic"> 
          <div class="screenshot"> 
           <a title="[field:title/]" href="[field:arcurl/]"> <img width="280" height="180" alt="[field:title/]" data-original="[field:picname/]" src="[field:global.cfg_cmsurl/]/skin/1.0/images/original.png" /> </a> 
          </div> 
          <h2 class="name"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2> 
         </div> 
         <div class="info"> 
          <div class="excerpt"> 
           <p>[field:description function="cn_substr(@me,60)"/]...</p> 
          </div> 
          <div class="pricebtn">
           <!--i>¥<strong>[field:needmoney/].00</strong></i-->
           <a class="buy" href="[field:arcurl/]">前往下载</a>
          </div> 
         </div> 
        </div> </li>