<?php
$z[0]=Array("picname","",225,241);
$z[1]=Array("picname","",248,264);
$z[2]=Array("title","",296,310);
$z[3]=Array("title","",617,631);
$z[4]=Array("title","",633,647);
$z[5]=Array("pubdate","",764,811);
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("dows","",879,892);
$z[7]=Array("dows","",929,942);
$z[8]=Array("click","",989,1003);
$z[9]=Array("click","",1039,1053);
$z[10]=Array("stows","",1101,1115);
$z[11]=Array("stows","",1167,1181);

?>