<?php
$z[0]=Array("global","",224,249);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",753,778);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",808,834);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",946,971);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1001,1027);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1070,1095);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n      <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      ",1133,1377);
$z[6][4]['type']="top";
$z[6][4]['row']="5";
$z[6][4]['currentstyle']="<li class='current-menu-item current_page_item'><a href='~typelink~' ~rel~>~typename~</a></li>";

?>