<?php
$z[0]=Array("global","",224,249);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",753,778);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",808,834);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",946,971);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1001,1027);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1065,1090);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n      <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      ",1128,1372);
$z[6][4]['type']="top";
$z[6][4]['row']="5";
$z[6][4]['currentstyle']="<li class='current-menu-item current_page_item'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[7]=Array("global","",1943,1968);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("hotwords","",2609,2663);
$z[8][4]['num']="15";
$z[8][4]['subday']="365";
$z[8][4]['maxlength']="16";

?>