<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('843', '/uploads/allimg/180531/qimaweb-1P531095253A4.jpg');
$maNum = 1;
$myaddons[$maNum] = array('844', '/uploads/allimg/180531/qimaweb-1P53113313N22.jpg');
$maNum = 2;
$myaddons[$maNum] = array('845', '/uploads/allimg/180531/qimaweb-1P531133A5331.jpg');
$maNum = 3;
$myaddons[$maNum] = array('846', '/uploads/allimg/180531/qimaweb-1P531134931304.jpg');
$maNum = 4;
$myaddons[$maNum] = array('847', '/uploads/allimg/180531/qimaweb-1P53113501EF.jpg');
$maNum = 5;
$myaddons[$maNum] = array('848', '/uploads/allimg/180531/qimaweb-1P53113512S56.jpg');
$maNum = 6;
$myaddons[$maNum] = array('849', '/uploads/allimg/180531/qimaweb-1P531142454636.png');
$maNum = 7;
