<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[4]=array(0,1,1,'572R56uZ6L2u5pKt');
$cfg_Cs[7]=array(0,1,1,'5ri45oiP5LuL57uN');
$cfg_Cs[20]=array(0,1,1,'5ri45oiP5LiL6L29');
$cfg_Cs[40]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[29]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[32]=array(0,1,1,'5ri45oiP5Lit5b+D');
$cfg_Cs[33]=array(32,1,1,'5ri45oiP5LuL57uN');
$cfg_Cs[34]=array(32,1,1,'5ri45oiP5LiL6L29');
$cfg_Cs[41]=array(0,1,1,'5ri45oiP5oiq5Zu+');
$cfg_Cs[35]=array(32,1,1,'5YWF5YC85Lit5b+D');
$cfg_Cs[36]=array(32,1,1,'5a626ZW/55uR5oqk5Lit5b+D');
$cfg_Cs[42]=array(0,1,1,'57qg57q35aSE55CG5rWB56iL');
$cfg_Cs[43]=array(0,1,1,'55So5oi35rOo5YaM5Y2P6K6u');
?>