<?php  exit();
/*
Page: /dede/sys_data.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-04-28 09:25:04
*/
?>
<?php  exit();
/*
Page: /i/ajax_login-reg.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-05-30 15:24:53
*/
?>
<?php  exit();
/*
Page: /i/ajax_login-reg.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-07-06 11:54:34
*/
?>
<?php  exit();
/*
Page: /i/ajax_login-reg.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-07-06 11:54:42
*/
?>
<?php  exit();
/*
Page: /i/ajax_login-reg.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-07-06 11:54:50
*/
?>
<?php  exit();
/*
Page: /i/ajax_login-reg.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-07-06 11:55:42
*/
?>
<?php  exit();
/*
Page: /i/ajax_login-reg.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-07-09 09:02:36
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-07-09 09:02:53
*/
?>
